@echo off
echo Initializing git...
git init
echo Setting branch to main...
git branch -M main
echo Adding remote...
git remote remove origin 2>nul
git remote add origin https://github.com/chinnivenkatesh/xeno_project.git
echo Staging files...
git add .
echo Committing...
git commit -m "Initial commit"
echo Setup complete.
